<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="admins-MacBook-4.local" name="Test demo" tests="4" failures="1" timestamp="7 Feb 2017 02:19:32 GMT" time="18.297" errors="0">
  <testcase name="test03_Method on [SecondRun passed=0 failed=0 skipped=0]" time="1.633" classname="demo.SecondRun"/>
  <testcase name="test01_Method on [FirstRun passed=0 failed=0 skipped=0]" time="1.631" classname="demo.FirstRun"/>
  <testcase name="test04_Method on [SecondRun passed=0 failed=0 skipped=0]" time="1.014" classname="demo.SecondRun"/>
  <testcase name="test02_Method on [FirstRun passed=0 failed=0 skipped=0]" time="2.459" classname="demo.FirstRun">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at demo.FirstRun.test02_Method(FirstRun.java:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- test02_Method on [FirstRun passed=0 failed=0 skipped=0] -->
</testsuite> <!-- Test demo -->
